import type { Metadata } from "next";
import { auth } from "@/auth";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { PublicHeader } from "@/components/full-access/header";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en" className="scroll-">
        <body className={cn(
          inter.className,
        "bg-no-repeat bg-cover bg-center bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-cyan-600 to-indigo-900")}
        >

          <PublicHeader />
          <Toaster />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
